### ISSUE TITLE
Signing a url with no query parameters fails

### ISSUE THREAD

**Issue by Xylakant** [Asquera/warden-hmac-authentication#7]
/home/vagrant/warden-hmac-authentication/lib/hmac_signer.rb:199:in `sign_request': undefined method`[]=' for nil:NilClass (NoMethodError)
    from /home/vagrant/warden-hmac-authentication/lib/hmac_signer.rb:228:in `sign_url'

**Comment by Xylakant** [comment]
fixed in 24d31b1
